[2025-02-05T01:13:12.381+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T01:13:12.396+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:13:11.399164+00:00 [queued]>
[2025-02-05T01:13:12.402+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:13:11.399164+00:00 [queued]>
[2025-02-05T01:13:12.402+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T01:13:12.413+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): load_postgres> on 2025-02-05 01:13:11.399164+00:00
[2025-02-05T01:13:12.419+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10353) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-05T01:13:12.420+0000] {standard_task_runner.py:72} INFO - Started process 10354 to run task
[2025-02-05T01:13:12.419+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_loader', 'load_postgres', 'manual__2025-02-05T01:13:11.399164+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_loader_mel.py', '--cfg-path', '/tmp/tmplsryl4d5']
[2025-02-05T01:13:12.420+0000] {standard_task_runner.py:105} INFO - Job 59: Subtask load_postgres
[2025-02-05T01:13:12.453+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:13:11.399164+00:00 [running]> on host 09d05643d017
[2025-02-05T01:13:12.519+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_loader' AIRFLOW_CTX_TASK_ID='load_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T01:13:11.399164+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T01:13:11.399164+00:00'
[2025-02-05T01:13:12.520+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T01:13:12.558+0000] {docker.py:379} INFO - Starting docker container from image meu-meltano
[2025-02-05T01:13:13.014+0000] {docker.py:73} INFO - + set -e
[2025-02-05T01:13:13.015+0000] {docker.py:73} INFO - + cd /meltano/demo-project
[2025-02-05T01:13:13.015+0000] {docker.py:73} INFO - + echo 'Iniciando processo...'
[2025-02-05T01:13:13.016+0000] {docker.py:73} INFO - + echo 'Instalando target-postgres...'
[2025-02-05T01:13:13.016+0000] {docker.py:73} INFO - + meltano add loader target-postgres
[2025-02-05T01:13:13.017+0000] {docker.py:73} INFO - Iniciando processo...
[2025-02-05T01:13:13.017+0000] {docker.py:73} INFO - Instalando target-postgres...
[2025-02-05T01:13:15.237+0000] {docker.py:73} INFO - Added loader 'target-postgres' to your project
[2025-02-05T01:13:15.237+0000] {docker.py:73} INFO - Variant:	meltanolabs (default)
[2025-02-05T01:13:15.238+0000] {docker.py:73} INFO - Repository:	https://github.com/MeltanoLabs/target-postgres
[2025-02-05T01:13:15.238+0000] {docker.py:73} INFO - Documentation:	https://hub.meltano.com/loaders/target-postgres--meltanolabs
[2025-02-05T01:13:15.301+0000] {docker.py:73} INFO - [2m2025-02-05T01:13:15.299743Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-02-05T01:13:31.331+0000] {docker.py:73} INFO - [2m2025-02-05T01:13:31.330510Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-02-05T01:13:31.332+0000] {docker.py:73} INFO - 
[2025-02-05T01:13:31.333+0000] {docker.py:73} INFO - To learn more about loader 'target-postgres', visit https://hub.meltano.com/loaders/target-postgres--meltanolabs
[2025-02-05T01:13:32.360+0000] {docker.py:73} INFO - Verificando instala√ß√£o:
[2025-02-05T01:13:32.360+0000] {docker.py:73} INFO - + echo 'Verificando instala√ß√£o:'
[2025-02-05T01:13:32.361+0000] {docker.py:73} INFO - + meltano list loaders
[2025-02-05T01:13:32.964+0000] {docker.py:73} INFO - Usage: meltano [OPTIONS] COMMAND [ARGS]...
[2025-02-05T01:13:32.965+0000] {docker.py:73} INFO - Try 'meltano --help' for help.
[2025-02-05T01:13:32.965+0000] {docker.py:73} INFO - 
[2025-02-05T01:13:32.965+0000] {docker.py:73} INFO - Error: No such command 'list'.
[2025-02-05T01:13:32.966+0000] {docker.py:73} INFO - 
[2025-02-05T01:13:32.966+0000] {docker.py:73} INFO - Did you mean one of these?
[2025-02-05T01:13:32.966+0000] {docker.py:73} INFO -     elt
[2025-02-05T01:13:32.967+0000] {docker.py:73} INFO -     install
[2025-02-05T01:13:32.967+0000] {docker.py:73} INFO -     test
[2025-02-05T01:13:33.870+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-02-05T01:13:33.877+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_loader, task_id=load_postgres, run_id=manual__2025-02-05T01:13:11.399164+00:00, execution_date=20250205T011311, start_date=20250205T011312, end_date=20250205T011333
[2025-02-05T01:13:33.887+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T01:13:33.888+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 59 for task load_postgres (Docker container failed: {'StatusCode': 2}; 10354)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-02-05T01:13:33.935+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-05T01:13:33.947+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T01:13:33.949+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
