[2025-02-05T01:23:50.275+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T01:23:50.288+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:23:49.155293+00:00 [queued]>
[2025-02-05T01:23:50.295+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:23:49.155293+00:00 [queued]>
[2025-02-05T01:23:50.296+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T01:23:50.306+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): load_postgres> on 2025-02-05 01:23:49.155293+00:00
[2025-02-05T01:23:50.312+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10837) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-05T01:23:50.313+0000] {standard_task_runner.py:72} INFO - Started process 10838 to run task
[2025-02-05T01:23:50.312+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_loader', 'load_postgres', 'manual__2025-02-05T01:23:49.155293+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_loader_mel.py', '--cfg-path', '/tmp/tmpavcm92ax']
[2025-02-05T01:23:50.313+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask load_postgres
[2025-02-05T01:23:50.347+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_loader.load_postgres manual__2025-02-05T01:23:49.155293+00:00 [running]> on host 09d05643d017
[2025-02-05T01:23:50.415+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_loader' AIRFLOW_CTX_TASK_ID='load_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T01:23:49.155293+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T01:23:49.155293+00:00'
[2025-02-05T01:23:50.415+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T01:23:50.456+0000] {docker.py:379} INFO - Starting docker container from image meu-meltano
[2025-02-05T01:23:51.078+0000] {docker.py:73} INFO - + set -e
[2025-02-05T01:23:51.078+0000] {docker.py:73} INFO - + cd /meltano/demo-project
[2025-02-05T01:23:51.079+0000] {docker.py:73} INFO - + echo 'Iniciando processo...'
[2025-02-05T01:23:51.079+0000] {docker.py:73} INFO - + echo 'Instalando target-postgres...'
[2025-02-05T01:23:51.080+0000] {docker.py:73} INFO - + meltano add loader target-postgres
[2025-02-05T01:23:51.080+0000] {docker.py:73} INFO - Iniciando processo...
[2025-02-05T01:23:51.081+0000] {docker.py:73} INFO - Instalando target-postgres...
[2025-02-05T01:23:53.258+0000] {docker.py:73} INFO - Added loader 'target-postgres' to your project
[2025-02-05T01:23:53.259+0000] {docker.py:73} INFO - Variant:	meltanolabs (default)
[2025-02-05T01:23:53.259+0000] {docker.py:73} INFO - Repository:	https://github.com/MeltanoLabs/target-postgres
[2025-02-05T01:23:53.259+0000] {docker.py:73} INFO - Documentation:	https://hub.meltano.com/loaders/target-postgres--meltanolabs
[2025-02-05T01:23:53.322+0000] {docker.py:73} INFO - [2m2025-02-05T01:23:53.321195Z[0m [[32m[1minfo     [0m] [1mInstalling loader 'target-postgres'[0m
[2025-02-05T01:24:12.727+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:12.725536Z[0m [[32m[1minfo     [0m] [1mInstalled loader 'target-postgres'[0m
[2025-02-05T01:24:12.728+0000] {docker.py:73} INFO - 
[2025-02-05T01:24:12.728+0000] {docker.py:73} INFO - To learn more about loader 'target-postgres', visit https://hub.meltano.com/loaders/target-postgres--meltanolabs
[2025-02-05T01:24:13.695+0000] {docker.py:73} INFO - Configurando target-postgres...
[2025-02-05T01:24:13.696+0000] {docker.py:73} INFO - + echo 'Configurando target-postgres...'
[2025-02-05T01:24:13.696+0000] {docker.py:73} INFO - + meltano --environment=dev config target-postgres set host northwind_db
[2025-02-05T01:24:14.338+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:14.336854Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T01:24:14.422+0000] {docker.py:73} INFO - Loader 'target-postgres' setting 'host' was set in the active environment in `meltano.yml`: 'northwind_db'
[2025-02-05T01:24:15.391+0000] {docker.py:73} INFO - + meltano --environment=dev config target-postgres set port 5432
[2025-02-05T01:24:16.015+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:16.014208Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T01:24:16.094+0000] {docker.py:73} INFO - Loader 'target-postgres' setting 'port' was set in the active environment in `meltano.yml`: 5432
[2025-02-05T01:24:17.062+0000] {docker.py:73} INFO - + meltano --environment=dev config target-postgres set user northwind_user
[2025-02-05T01:24:17.691+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:17.690408Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T01:24:17.773+0000] {docker.py:73} INFO - Loader 'target-postgres' setting 'user' was set in the active environment in `meltano.yml`: 'northwind_user'
[2025-02-05T01:24:18.751+0000] {docker.py:73} INFO - + meltano --environment=dev config target-postgres set password thewindisblowing
[2025-02-05T01:24:19.385+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:19.383697Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T01:24:19.452+0000] {docker.py:73} INFO - Loader 'target-postgres' setting 'password' was set in `.env`: (redacted)
[2025-02-05T01:24:20.420+0000] {docker.py:73} INFO - + meltano --environment=dev config target-postgres set database northwind
[2025-02-05T01:24:21.042+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:21.041291Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T01:24:21.123+0000] {docker.py:73} INFO - Loader 'target-postgres' setting 'database' was set in the active environment in `meltano.yml`: 'northwind'
[2025-02-05T01:24:22.083+0000] {docker.py:73} INFO - + meltano --environment=dev config target-postgres set default_target_schema public
[2025-02-05T01:24:22.730+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:22.729069Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T01:24:22.811+0000] {docker.py:73} INFO - Loader 'target-postgres' setting 'default_target_schema' was set in the active environment in `meltano.yml`: 'public'
[2025-02-05T01:24:23.773+0000] {docker.py:73} INFO - + meltano --environment=dev config target-postgres set schema_mapping '{
[2025-02-05T01:24:23.774+0000] {docker.py:73} INFO -             "order_details": {
[2025-02-05T01:24:23.774+0000] {docker.py:73} INFO -                 "order_id": "smallint",
[2025-02-05T01:24:23.775+0000] {docker.py:73} INFO -                 "product_id": "smallint",
[2025-02-05T01:24:23.775+0000] {docker.py:73} INFO -                 "unit_price": "real",
[2025-02-05T01:24:23.775+0000] {docker.py:73} INFO -                 "quantity": "smallint",
[2025-02-05T01:24:23.776+0000] {docker.py:73} INFO -                 "discount": "real"
[2025-02-05T01:24:23.776+0000] {docker.py:73} INFO -             }
[2025-02-05T01:24:23.776+0000] {docker.py:73} INFO -         }'
[2025-02-05T01:24:24.396+0000] {docker.py:73} INFO - [2m2025-02-05T01:24:24.394802Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T01:24:24.465+0000] {docker.py:73} INFO - /usr/local/lib/python3.10/site-packages/meltano/cli/interactive/config.py:403: RuntimeWarning: Unknown setting 'schema_mapping'
[2025-02-05T01:24:24.465+0000] {docker.py:73} INFO -   value, metadata = settings.set_with_metadata(
[2025-02-05T01:24:24.480+0000] {docker.py:73} INFO - Loader 'target-postgres' setting 'schema_mapping' was set in the active environment in `meltano.yml`: '{\n            "order_details": {\n                "order_id": "smallint",\n                "product_id": "smallint",\n                "unit_price": "real",\n                "quantity": "smallint",\n                "discount": "real"\n            }\n        }'
[2025-02-05T01:24:25.435+0000] {docker.py:73} INFO - + PGPASSWORD=thewindisblowing
[2025-02-05T01:24:25.436+0000] {docker.py:73} INFO - + psql -h northwind_db -U northwind_user -d northwind -c 'DROP TABLE IF EXISTS order_details;'
[2025-02-05T01:24:25.436+0000] {docker.py:73} INFO - bash: line 31: psql: command not found
[2025-02-05T01:24:26.967+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 127}
[2025-02-05T01:24:26.972+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_loader, task_id=load_postgres, run_id=manual__2025-02-05T01:23:49.155293+00:00, execution_date=20250205T012349, start_date=20250205T012350, end_date=20250205T012426
[2025-02-05T01:24:26.982+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T01:24:26.983+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 63 for task load_postgres (Docker container failed: {'StatusCode': 127}; 10838)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 127}
[2025-02-05T01:24:27.004+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-05T01:24:27.023+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T01:24:27.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
