[2025-02-04T20:09:44.220+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T20:09:44.235+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_meltano.test_meltano manual__2025-02-04T20:09:43.061453+00:00 [queued]>
[2025-02-04T20:09:44.241+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_meltano.test_meltano manual__2025-02-04T20:09:43.061453+00:00 [queued]>
[2025-02-04T20:09:44.242+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-04T20:09:44.252+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): test_meltano> on 2025-02-04 20:09:43.061453+00:00
[2025-02-04T20:09:44.258+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_meltano', 'test_meltano', 'manual__2025-02-04T20:09:43.061453+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_meltano.py', '--cfg-path', '/tmp/tmpzjk36jnx']
[2025-02-04T20:09:44.260+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask test_meltano
[2025-02-04T20:09:44.262+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-04T20:09:44.262+0000] {standard_task_runner.py:72} INFO - Started process 219 to run task
[2025-02-04T20:09:44.297+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_meltano.test_meltano manual__2025-02-04T20:09:43.061453+00:00 [running]> on host bc28df93379b
[2025-02-04T20:09:44.369+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_meltano' AIRFLOW_CTX_TASK_ID='test_meltano' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T20:09:43.061453+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T20:09:43.061453+00:00'
[2025-02-04T20:09:44.369+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T20:09:44.420+0000] {docker.py:379} INFO - Starting docker container from image meu-meltano
[2025-02-04T20:09:44.427+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-04T20:09:45.804+0000] {docker.py:73} INFO - meltano, version 3.6.0
[2025-02-04T20:09:46.389+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T20:09:46.390+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=northwind_meltano, task_id=test_meltano, run_id=manual__2025-02-04T20:09:43.061453+00:00, execution_date=20250204T200943, start_date=20250204T200944, end_date=20250204T200946
[2025-02-04T20:09:46.443+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T20:09:46.456+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T20:09:46.459+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
