[2025-02-04T20:27:26.523+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T20:27:26.537+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_meltano.setup_meltano manual__2025-02-04T20:27:25.421814+00:00 [queued]>
[2025-02-04T20:27:26.543+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_meltano.setup_meltano manual__2025-02-04T20:27:25.421814+00:00 [queued]>
[2025-02-04T20:27:26.544+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-04T20:27:26.556+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): setup_meltano> on 2025-02-04 20:27:25.421814+00:00
[2025-02-04T20:27:26.561+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_meltano', 'setup_meltano', 'manual__2025-02-04T20:27:25.421814+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_meltano.py', '--cfg-path', '/tmp/tmppp73xk8_']
[2025-02-04T20:27:26.563+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask setup_meltano
[2025-02-04T20:27:26.563+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=345) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-04T20:27:26.564+0000] {standard_task_runner.py:72} INFO - Started process 348 to run task
[2025-02-04T20:27:26.598+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_meltano.setup_meltano manual__2025-02-04T20:27:25.421814+00:00 [running]> on host 09d05643d017
[2025-02-04T20:27:26.670+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_meltano' AIRFLOW_CTX_TASK_ID='setup_meltano' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T20:27:25.421814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T20:27:25.421814+00:00'
[2025-02-04T20:27:26.671+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T20:27:26.718+0000] {docker.py:379} INFO - Starting docker container from image meu-meltano
[2025-02-04T20:27:30.514+0000] {docker.py:73} INFO - Added extractor 'tap-postgres' to your project
[2025-02-04T20:27:30.515+0000] {docker.py:73} INFO - Variant:	meltanolabs (default)
[2025-02-04T20:27:30.515+0000] {docker.py:73} INFO - Repository:	https://github.com/MeltanoLabs/tap-postgres
[2025-02-04T20:27:30.516+0000] {docker.py:73} INFO - Documentation:	https://hub.meltano.com/extractors/tap-postgres--meltanolabs
[2025-02-04T20:27:30.657+0000] {docker.py:73} INFO - [2m2025-02-04T20:27:30.655783Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-postgres'[0m
[2025-02-04T20:27:55.030+0000] {docker.py:73} INFO - [2m2025-02-04T20:27:55.029231Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-postgres'[0m
[2025-02-04T20:27:55.031+0000] {docker.py:73} INFO - 
[2025-02-04T20:27:55.031+0000] {docker.py:73} INFO - To learn more about extractor 'tap-postgres', visit https://hub.meltano.com/extractors/tap-postgres--meltanolabs
[2025-02-04T20:27:56.624+0000] {docker.py:73} INFO - [2m2025-02-04T20:27:56.623297Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-04T20:27:56.768+0000] {docker.py:73} INFO - Extractor 'tap-postgres' setting 'host' was set in the active environment in `meltano.yml`: 'northwind_db'
[2025-02-04T20:27:58.357+0000] {docker.py:73} INFO - [2m2025-02-04T20:27:58.356198Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-04T20:27:58.436+0000] {docker.py:73} INFO - Extractor 'tap-postgres' setting 'port' was set in the active environment in `meltano.yml`: 5432
[2025-02-04T20:28:00.044+0000] {docker.py:73} INFO - [2m2025-02-04T20:28:00.042949Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-04T20:28:00.125+0000] {docker.py:73} INFO - Extractor 'tap-postgres' setting 'user' was set in the active environment in `meltano.yml`: 'northwind_user'
[2025-02-04T20:28:01.761+0000] {docker.py:73} INFO - [2m2025-02-04T20:28:01.759679Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-04T20:28:01.828+0000] {docker.py:73} INFO - Extractor 'tap-postgres' setting 'password' was set in `.env`: (redacted)
[2025-02-04T20:28:03.414+0000] {docker.py:73} INFO - [2m2025-02-04T20:28:03.413429Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-04T20:28:03.495+0000] {docker.py:73} INFO - Extractor 'tap-postgres' setting 'database' was set in the active environment in `meltano.yml`: 'northwind'
[2025-02-04T20:28:05.078+0000] {docker.py:73} INFO - [2m2025-02-04T20:28:05.076972Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-04T20:28:05.145+0000] {docker.py:73} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
[2025-02-04T20:28:05.145+0000] {docker.py:73} INFO - join our friendly Slack community.
[2025-02-04T20:28:05.146+0000] {docker.py:73} INFO - 
[2025-02-04T20:28:05.146+0000] {docker.py:73} INFO - Failed to parse JSON array from string: 'public'
[2025-02-04T20:28:08.022+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-04T20:28:08.026+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_meltano, task_id=setup_meltano, run_id=manual__2025-02-04T20:27:25.421814+00:00, execution_date=20250204T202725, start_date=20250204T202726, end_date=20250204T202808
[2025-02-04T20:28:08.038+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T20:28:08.038+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task setup_meltano (Docker container failed: {'StatusCode': 1}; 348)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-04T20:28:08.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-04T20:28:08.086+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T20:28:08.088+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
