[2025-02-05T00:40:22.168+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T00:40:22.181+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: northwind_meltano.extract_csv manual__2025-02-05T00:39:20.913783+00:00 [queued]>
[2025-02-05T00:40:22.187+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: northwind_meltano.extract_csv manual__2025-02-05T00:39:20.913783+00:00 [queued]>
[2025-02-05T00:40:22.188+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-05T00:40:22.199+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_csv> on 2025-02-05 00:39:20.913783+00:00
[2025-02-05T00:40:22.204+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9085) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-05T00:40:22.204+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'northwind_meltano', 'extract_csv', 'manual__2025-02-05T00:39:20.913783+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/northwind_etl/northwind_meltano.py', '--cfg-path', '/tmp/tmpwv6_lgg0']
[2025-02-05T00:40:22.205+0000] {standard_task_runner.py:72} INFO - Started process 9086 to run task
[2025-02-05T00:40:22.206+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask extract_csv
[2025-02-05T00:40:22.238+0000] {task_command.py:467} INFO - Running <TaskInstance: northwind_meltano.extract_csv manual__2025-02-05T00:39:20.913783+00:00 [running]> on host 09d05643d017
[2025-02-05T00:40:22.303+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gabriel' AIRFLOW_CTX_DAG_ID='northwind_meltano' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T00:39:20.913783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T00:39:20.913783+00:00'
[2025-02-05T00:40:22.303+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T00:40:22.347+0000] {docker.py:379} INFO - Starting docker container from image meu-meltano
[2025-02-05T00:40:22.985+0000] {docker.py:73} INFO - Conte√∫do do diret√≥rio input:
[2025-02-05T00:40:22.995+0000] {docker.py:73} INFO - total 300
[2025-02-05T00:40:23.005+0000] {docker.py:73} INFO - drwxrwxrwx 1 50000 root   4096 Feb  5 00:31 .
[2025-02-05T00:40:23.006+0000] {docker.py:73} INFO - drwxr-xr-x 1 root  root   4096 Feb  5 00:40 ..
[2025-02-05T00:40:23.006+0000] {docker.py:73} INFO - drwxrwxr-x 1 50000 root   4096 Feb  5 00:38 csv
[2025-02-05T00:40:23.006+0000] {docker.py:73} INFO - -rwxrwxrwx 1 50000 root 213209 Jan 29 20:37 northwind.sql
[2025-02-05T00:40:23.007+0000] {docker.py:73} INFO - -rwxrwxrwx 1 50000 root  42781 Jan 29 20:37 order_details.csv
[2025-02-05T00:40:23.007+0000] {docker.py:73} INFO - drwxrwxrwx 1 50000 root   4096 Feb  5 00:27 postgres
[2025-02-05T00:40:23.007+0000] {docker.py:73} INFO - -rw-r--r-- 1 root  root  37121 Feb  4 21:42 postgres_config.json
[2025-02-05T00:40:25.628+0000] {docker.py:73} INFO - Added extractor 'tap-csv' to your project
[2025-02-05T00:40:25.628+0000] {docker.py:73} INFO - Variant:	meltanolabs (default)
[2025-02-05T00:40:25.629+0000] {docker.py:73} INFO - Repository:	https://github.com/MeltanoLabs/tap-csv
[2025-02-05T00:40:25.629+0000] {docker.py:73} INFO - Documentation:	https://hub.meltano.com/extractors/tap-csv--meltanolabs
[2025-02-05T00:40:25.681+0000] {docker.py:73} INFO - [2m2025-02-05T00:40:25.680176Z[0m [[32m[1minfo     [0m] [1mInstalling extractor 'tap-csv'[0m
[2025-02-05T00:40:42.819+0000] {docker.py:73} INFO - [2m2025-02-05T00:40:42.818025Z[0m [[32m[1minfo     [0m] [1mInstalled extractor 'tap-csv' [0m
[2025-02-05T00:40:42.819+0000] {docker.py:73} INFO - 
[2025-02-05T00:40:42.820+0000] {docker.py:73} INFO - To learn more about extractor 'tap-csv', visit https://hub.meltano.com/extractors/tap-csv--meltanolabs
[2025-02-05T00:40:43.786+0000] {docker.py:73} INFO - Conte√∫do do arquivo de configura√ß√£o:
[2025-02-05T00:40:43.788+0000] {docker.py:73} INFO - {
[2025-02-05T00:40:43.788+0000] {docker.py:73} INFO -             "files": [
[2025-02-05T00:40:43.789+0000] {docker.py:73} INFO -                 "/meltano/demo-project/input/order_details.csv"
[2025-02-05T00:40:43.789+0000] {docker.py:73} INFO -             ]
[2025-02-05T00:40:43.789+0000] {docker.py:73} INFO -         }
[2025-02-05T00:40:44.417+0000] {docker.py:73} INFO - [2m2025-02-05T00:40:44.415824Z[0m [[32m[1minfo     [0m] [1mThe default environment 'dev' will be ignored for `meltano config`. To configure a specific environment, please use the option `--environment=<environment name>`.[0m
[2025-02-05T00:40:44.468+0000] {docker.py:73} INFO - /usr/local/lib/python3.10/site-packages/meltano/cli/interactive/config.py:403: RuntimeWarning: Unknown setting '_load_config'
[2025-02-05T00:40:44.469+0000] {docker.py:73} INFO -   value, metadata = settings.set_with_metadata(
[2025-02-05T00:40:44.482+0000] {docker.py:73} INFO - Extractor 'tap-csv' setting '_load_config' was set in `meltano.yml`: 'tap-csv-config.json'
[2025-02-05T00:40:46.084+0000] {docker.py:73} INFO - [2m2025-02-05T00:40:46.083022Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2025-02-05T00:40:46.765+0000] {docker.py:73} INFO - Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
[2025-02-05T00:40:46.766+0000] {docker.py:73} INFO - join our friendly Slack community.
[2025-02-05T00:40:46.766+0000] {docker.py:73} INFO - 
[2025-02-05T00:40:46.767+0000] {docker.py:73} INFO - Catalog discovery failed: command ['/meltano/demo-project/.meltano/extractors/tap-csv/venv/bin/tap-csv', '--config', '/meltano/demo-project/.meltano/run/tap-csv/tap.6671144b-2b4e-436c-a991-43a555e2cde6.config.json', '--discover'] returned 1 with stderr:
[2025-02-05T00:40:46.767+0000] {docker.py:73} INFO -  2025-02-05 00:40:46,697 | ERROR    | tap-csv              | No CSV file definitions found.
[2025-02-05T00:40:49.049+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-05T00:40:49.053+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=northwind_meltano, task_id=extract_csv, run_id=manual__2025-02-05T00:39:20.913783+00:00, execution_date=20250205T003920, start_date=20250205T004022, end_date=20250205T004049
[2025-02-05T00:40:49.063+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T00:40:49.064+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 47 for task extract_csv (Docker container failed: {'StatusCode': 1}; 9086)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 519, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 396, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 453, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-02-05T00:40:49.109+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-05T00:40:49.124+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T00:40:49.126+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
